- name: Wait for SONiC SSH daemon to start
  wait_for_connection:
    timeout: 60
  when: ansible_connection == 'network_cli'

- name: Execute local ssh command to check SONiC readiness
  local_action:
    module: command
    cmd: "sshpass -p '{{ ansible_ssh_pass }}' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ ansible_user }}@{{ ansible_host }} 'show system status brief'"
  register: command_out
  until: command_out.stdout is 'System is ready'
  retries: 10
  delay: 30
  when: libvirt.kind is defined

